### ISSUE TITLE
Getting rid of startup errors: Event orphaned

### ISSUE THREAD

**Issue by Serpens66** [Gr770/UnifiedUICK3#16]
Following your modder guide here: https://github.com/Gr770/UnifiedUICK3/wiki/Global-Variables
"Getting rid of startup errors", I now get the startup error: 

[13:00:42][jomini_eventmanager.cpp:367]: Event knight_manager_mod_error_suppression.0001 is orphaned

So is it just replacing "Variable ... is set but is never used" with this orphaned error? Or did I do something wrong? 
https://steamcommunity.com/sharedfiles/filedetails/?id=2645646874

```
# just needed for UniUI compatibilty
# suppressoin of the error : Variable '<your_mod_name>_is_loaded' is set but is never used

namespace = knight_manager_mod_error_suppression

knight_manager_mod_error_suppression.0001 = {
	hidden = yes
    trigger = {
        exists = global_var:KnightManager_is_loaded
    }
    effect = {
    }
}
```

**Comment by terrapass** [comment]
Hi. This is a new error that became a thing after the guide was written.
Try adding `orphan = yes` in addition to `hidden = yes` to suppress it.

**Comment by Serpens66** [comment]
ok, added orphan and also had to remove "effect" , because this caused:
[14:03:42][pdx_persistent_reader.cpp:250]: Error: "Unexpected token: effect, near line: 12" in file: "events/knight_manager_events.txt" near line: 13

I looks like this now and I see no more error:
```
# just needed for UniUI compatibilty
# suppressoin of the error : Variable '<your_mod_name>_is_loaded' is set but is never used

namespace = knight_manager_mod_error_suppression

knight_manager_mod_error_suppression.0001 = {
    hidden = yes
    orphan = yes
    trigger = {
        exists = global_var:KnightManager_is_loaded
    }
}
```

**Comment by terrapass** [comment]
Great. I updated the doc accordingly.
